---
- name: Deploy LAMP Stack
  hosts: worker-nodes
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Check if Apache configuration file exists
      stat:
        path: /etc/apache2/apache2.conf
      register: apache_config

    - name: Reinstall Apache if configuration file is missing
      apt:
        name: apache2
        state: reinstalled
      when: not apache_config.stat.exists

    - name: Test Apache configuration
      command: apachectl configtest
      register: apache_configtest
      failed_when: "'Syntax OK' not in apache_configtest.stdout"
      when: apache_config.stat.exists

    - name: Report Apache configuration test result
      debug:
        msg: "{{ apache_configtest.stdout }}"
      when: apache_config.stat.exists and apache_configtest.failed

    - name: Start and enable Apache
      systemd:
        name: apache2
        state: started
        enabled: yes
      notify: restart apache
      when: apache_config.stat.exists

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Ensure MySQL is started and enabled
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password and remove anonymous users
      mysql_user:
        name: root
        password: 'root_password'
        host: localhost
        priv: "*.*:ALL"
        state: present
        update_password: always
      ignore_errors: yes

    - name: Remove test database
      mysql_db:
        name: test
        state: absent
      ignore_errors: yes

    - name: Install PHP and modules
      apt:
        name:
          - php
          - php-mysql
          - php-xml
        state: present

    - name: Ensure Apache is configured to serve PHP
      copy:
        src: /etc/apache2/mods-available/php7.4.conf
        dest: /etc/apache2/mods-enabled/php7.4.conf
      notify: restart apache

  handlers:
    - name: restart apache
      systemd:
        name: apache2
        state: restarted
