---
- name: Upgrade Java from 11 to 17
  hosts: worker-nodes
  become: yes
  tasks:
    - name: Remove existing Java 11
      apt:
        name: openjdk-11-jdk
        state: absent
      when: ansible_distribution == 'Ubuntu'

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
        
    - name: Set Java 17 as default
      alternatives:
        name: java
        path: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
        priority: 1
      when: ansible_distribution == 'Ubuntu'
